name: Nick
version: '2.5'
main: me.sk8ingduck.nick.Nick
authors: [ sk8ingDuck ]

depend:
  - PlaceholderAPI

softdepend:
  - TAB
  - NametagEdit
  - LuckPerms

commands:
  nick:
    description: nick yourself
    usage: /nick
  unnick:
    description: unnick yourself
    usage: /unnick